[DEFAULT]
;ScreenSize = 640, 480
ScreenSize = auto
FullScreen = 1

; Цвет фона и шрифта задается в шестнадцатиртчном виде или словами
; например BackgroundColor = RRGGBB, где RR - красный цвет (hex), GG - зеленый, BB - синий 
; или BackgroundColor = blue
 
BackgroundColor = 0066ff
BackgroundColorAlarm = cc3333
BackgroundColorPass = 008833
BackgroundFile = media/geometriya.png
BackgroundFileAlarm = media/geometriya_alarm.png
BackgroundFilePAss = media/geometriya_pass.png

Font = fonts/InputMono-BlackItalic.ttf
FontColor = yellow

;Уровень логирования
;Возможны варианты:
;    DEBUG - подробгый лог для отладки,
;    INFO - информационные сообщения и ошибки (по умолчанию)
;    ERROR - только ошибки
LogLevel = INFO
